"""initial schema

Revision ID: 7b835d0aef2b
Revises: 
Create Date: 2026-07-22 00:27:19.268782
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7b835d0aef2b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trace_id', sa.String(length=64), nullable=False),
    sa.Column('method', sa.String(length=20), nullable=False),
    sa.Column('path', sa.String(length=1000), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('actor', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_path'), 'audit_logs', ['path'], unique=False)
    op.create_index(op.f('ix_audit_logs_trace_id'), 'audit_logs', ['trace_id'], unique=False)
    op.create_table('background_jobs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('job_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=200), nullable=False),
    sa.Column('available_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_background_jobs_idempotency_key'), 'background_jobs', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_background_jobs_job_type'), 'background_jobs', ['job_type'], unique=False)
    op.create_index(op.f('ix_background_jobs_status'), 'background_jobs', ['status'], unique=False)
    op.create_table('chunk_embeddings',
    sa.Column('chunk_id', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=200), nullable=False),
    sa.Column('vector', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('chunk_id', 'provider', 'model')
    )
    op.create_table('compliance_checks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('external_id', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=True),
    sa.Column('product_payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compliance_checks_external_id'), 'compliance_checks', ['external_id'], unique=False)
    op.create_table('compliance_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('version', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('pattern', sa.String(length=200), nullable=False),
    sa.Column('target_field', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('suggestion', sa.Text(), nullable=False),
    sa.Column('source_url', sa.String(length=1000), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compliance_rules_code'), 'compliance_rules', ['code'], unique=False)
    op.create_table('evaluation_reviews',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dataset', sa.String(length=200), nullable=False),
    sa.Column('sample_id', sa.String(length=100), nullable=False),
    sa.Column('decision', sa.String(length=30), nullable=False),
    sa.Column('expected_section_id', sa.String(length=200), nullable=True),
    sa.Column('reviewer', sa.String(length=100), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dataset', 'sample_id', name='uq_evaluation_review_sample')
    )
    op.create_index(op.f('ix_evaluation_reviews_dataset'), 'evaluation_reviews', ['dataset'], unique=False)
    op.create_index(op.f('ix_evaluation_reviews_decision'), 'evaluation_reviews', ['decision'], unique=False)
    op.create_index(op.f('ix_evaluation_reviews_sample_id'), 'evaluation_reviews', ['sample_id'], unique=False)
    op.create_table('policy_documents',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('source_url', sa.String(length=1000), nullable=False),
    sa.Column('publisher', sa.String(length=300), nullable=False),
    sa.Column('version', sa.String(length=100), nullable=False),
    sa.Column('published_at', sa.String(length=40), nullable=False),
    sa.Column('retrieved_at', sa.String(length=40), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_url', 'version', name='uq_source_version')
    )
    op.create_table('workflow_runs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('current_step', sa.String(length=100), nullable=False),
    sa.Column('input_payload', sa.JSON(), nullable=False),
    sa.Column('result_payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_runs_status'), 'workflow_runs', ['status'], unique=False)
    op.create_table('agent_memories',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('task_type', sa.String(length=60), nullable=False),
    sa.Column('jurisdictions', sa.JSON(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('channel', sa.String(length=100), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('outcome', sa.JSON(), nullable=False),
    sa.Column('source_versions', sa.JSON(), nullable=False),
    sa.Column('reviewed_by', sa.String(length=100), nullable=False),
    sa.Column('review_status', sa.String(length=30), nullable=False),
    sa.Column('invalidated_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['workflow_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_memories_category'), 'agent_memories', ['category'], unique=False)
    op.create_index(op.f('ix_agent_memories_channel'), 'agent_memories', ['channel'], unique=False)
    op.create_index(op.f('ix_agent_memories_review_status'), 'agent_memories', ['review_status'], unique=False)
    op.create_index(op.f('ix_agent_memories_run_id'), 'agent_memories', ['run_id'], unique=True)
    op.create_index(op.f('ix_agent_memories_task_type'), 'agent_memories', ['task_type'], unique=False)
    op.create_table('findings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('check_id', sa.String(length=36), nullable=False),
    sa.Column('rule_code', sa.String(length=100), nullable=False),
    sa.Column('rule_version', sa.String(length=40), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('matched_text', sa.String(length=500), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=False),
    sa.Column('suggestion', sa.Text(), nullable=False),
    sa.Column('source_url', sa.String(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['check_id'], ['compliance_checks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_findings_check_id'), 'findings', ['check_id'], unique=False)
    op.create_table('policy_chunks',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('document_id', sa.String(length=64), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.String(length=100), nullable=False),
    sa.Column('heading', sa.String(length=500), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['policy_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policy_chunks_document_id'), 'policy_chunks', ['document_id'], unique=False)
    op.create_index(op.f('ix_policy_chunks_section_id'), 'policy_chunks', ['section_id'], unique=False)
    op.create_table('policy_scopes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.String(length=64), nullable=False),
    sa.Column('jurisdiction', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('channel', sa.String(length=100), nullable=False),
    sa.Column('legal_level', sa.String(length=40), nullable=False),
    sa.Column('source_language', sa.String(length=20), nullable=False),
    sa.Column('translation_status', sa.String(length=40), nullable=False),
    sa.Column('effective_from', sa.String(length=40), nullable=False),
    sa.Column('effective_to', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['policy_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policy_scopes_category'), 'policy_scopes', ['category'], unique=False)
    op.create_index(op.f('ix_policy_scopes_channel'), 'policy_scopes', ['channel'], unique=False)
    op.create_index(op.f('ix_policy_scopes_document_id'), 'policy_scopes', ['document_id'], unique=False)
    op.create_index(op.f('ix_policy_scopes_jurisdiction'), 'policy_scopes', ['jurisdiction'], unique=False)
    op.create_table('workflow_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('step', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['workflow_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_events_run_id'), 'workflow_events', ['run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workflow_events_run_id'), table_name='workflow_events')
    op.drop_table('workflow_events')
    op.drop_index(op.f('ix_policy_scopes_jurisdiction'), table_name='policy_scopes')
    op.drop_index(op.f('ix_policy_scopes_document_id'), table_name='policy_scopes')
    op.drop_index(op.f('ix_policy_scopes_channel'), table_name='policy_scopes')
    op.drop_index(op.f('ix_policy_scopes_category'), table_name='policy_scopes')
    op.drop_table('policy_scopes')
    op.drop_index(op.f('ix_policy_chunks_section_id'), table_name='policy_chunks')
    op.drop_index(op.f('ix_policy_chunks_document_id'), table_name='policy_chunks')
    op.drop_table('policy_chunks')
    op.drop_index(op.f('ix_findings_check_id'), table_name='findings')
    op.drop_table('findings')
    op.drop_index(op.f('ix_agent_memories_task_type'), table_name='agent_memories')
    op.drop_index(op.f('ix_agent_memories_run_id'), table_name='agent_memories')
    op.drop_index(op.f('ix_agent_memories_review_status'), table_name='agent_memories')
    op.drop_index(op.f('ix_agent_memories_channel'), table_name='agent_memories')
    op.drop_index(op.f('ix_agent_memories_category'), table_name='agent_memories')
    op.drop_table('agent_memories')
    op.drop_index(op.f('ix_workflow_runs_status'), table_name='workflow_runs')
    op.drop_table('workflow_runs')
    op.drop_table('policy_documents')
    op.drop_index(op.f('ix_evaluation_reviews_sample_id'), table_name='evaluation_reviews')
    op.drop_index(op.f('ix_evaluation_reviews_decision'), table_name='evaluation_reviews')
    op.drop_index(op.f('ix_evaluation_reviews_dataset'), table_name='evaluation_reviews')
    op.drop_table('evaluation_reviews')
    op.drop_index(op.f('ix_compliance_rules_code'), table_name='compliance_rules')
    op.drop_table('compliance_rules')
    op.drop_index(op.f('ix_compliance_checks_external_id'), table_name='compliance_checks')
    op.drop_table('compliance_checks')
    op.drop_table('chunk_embeddings')
    op.drop_index(op.f('ix_background_jobs_status'), table_name='background_jobs')
    op.drop_index(op.f('ix_background_jobs_job_type'), table_name='background_jobs')
    op.drop_index(op.f('ix_background_jobs_idempotency_key'), table_name='background_jobs')
    op.drop_table('background_jobs')
    op.drop_index(op.f('ix_audit_logs_trace_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_path'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
